# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 19:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dossier', models.CharField(blank=True, max_length=200, null=True)),
                ('pseudoT411', models.CharField(max_length=42, null=True)),
                ('uid', models.IntegerField(null=True)),
                ('token', models.CharField(max_length=50, null=True)),
                ('downloaded', models.IntegerField(default=0, null=True)),
                ('uploaded', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='T411',
            fields=[
                ('profil_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='t411.Profil')),
            ],
            bases=('t411.profil',),
        ),
        migrations.AddField(
            model_name='profil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
