# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('t411', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateField()),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t411.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_t411', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('taille', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='historique',
            name='torrent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t411.Torrent'),
        ),
        migrations.AddField(
            model_name='profil',
            name='torrents',
            field=models.ManyToManyField(through='t411.Historique', to='t411.Torrent'),
        ),
    ]
