# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('t411', '0003_auto_20160403_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='menus',
        ),
        migrations.AddField(
            model_name='menu',
            name='profil',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='t411.Profil'),
        ),
    ]
