# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t411', '0004_auto_20160403_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('nom', models.CharField(max_length=40)),
            ],
        ),
    ]
