# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('t411', '0005_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='SousCategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('nom', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='categorie',
            old_name='cid',
            new_name='pid',
        ),
        migrations.AddField(
            model_name='souscategorie',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t411.Categorie'),
        ),
    ]
