# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('t411', '0006_auto_20160408_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='souscategorie',
            name='nom',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='souscategorie',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='t411.Categorie'),
        ),
    ]
