# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-26 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t411', '0007_auto_20160409_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='dossier_temp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
