#!/bin/bash

NAME="RuFy"                                  # Name of the application
DJANGODIR=$(readlink -f $(dirname $0))

VIRTUALDIR=venv                              # Python  directory

SOCKFILE=${DJANGODIR}/run/gunicorn.sock  # we will communicte using this unix socket
PORTNUMBER=8000

USER=rufy                                        # the user to run as
GROUP=web                                        # the group to run as

NUM_WORKERS=3                                    # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=RuFy.settings             # which settings file should Django use
DJANGO_WSGI_MODULE=RuFy.wsgi                     # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source ${VIRTUALDIR}/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec  ${VIRTUALDIR}/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --bind=127.0.0.1:${PORTNUMBER} \
  --log-level=debug \
  --log-file=log/gunicorn.log \
  --limit-request-field_size 0 \
  --timeout 60